<LoginPage>:
    FloatLayout:
        canvas:
            Rectangle:
                size: self.size
                pos: self.pos
                source: "icones/bg1.png"

# titulo da página de login - nome do aplicativo
        Label:
            pos_hint: {"right": 0.9, "top": 0.9}
            size_hint: 0.8, 0.2
            text: "CONTROLE DE [color=#00CFDB]VENDAS - HASHTAG[/color]"
            bold: True
            markup: True

# campos de preenchimento pro usuário logar no sistema
        TextInput:
            pos_hint: {"right": 0.9, "top": 0.7}
            size_hint: 0.8, 0.1
            id: email
            hint_text: "E-mail"
        TextInput:
            pos_hint: {"right": 0.9, "top": 0.55}
            size_hint: 0.8, 0.1
            id: senha
            hint_text: "Senha"
            password: True

# mensagem dinamica para exibição de possíveis erros na hora do usuário se logar / pedindo para se logar
        Label:
            id: mensagem_login
            pos_hint:{"right": 0.9, "top": 0.4}
            size_hint: 0.8, 0.1
            text: "[color=#00CFDB]Faça seu Login[/color]"
            bold: True
            markup: True

# label buttons com imagens no fundo para que usuário clique e se logue ou crie contas
        LabelButton:
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: self.size
                    source: "icones/botao.png" if self.state=="normal" else "icones/botao_apertado.png"
            pos_hint: {"right": 0.45, "top": 0.3}
            size_hint: 0.4, 0.2
            text: "Faça login"
            on_release: app.firebase.fazer_login(email.text, senha.text)
        LabelButton:
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: self.size
                    source: "icones/botao.png" if self.state=="normal" else "icones/botao_apertado.png"
            pos_hint: {"right": 0.95, "top": 0.3}
            size_hint: 0.4, 0.2
            text: "Crie sua conta"
            on_release: app.firebase.criar_conta(email.text, senha.text) # ids de email e senha que foram preenchidos