<MudarFoto>:
    FloatLayout:
        canvas.before:
            Rectangle:
                size: self.size
                pos: self.pos
                source: "icones/bg1.png"

        Label:
            pos_hint: {"right":0.85, "top":0.95}
            size_hint: 0.7, 0.2
            bold: True
            text: "Selecione sua foto foto de perfil"

        # lista de imagens
        ScrollView:
            pos_hint: {"right": 0.9, "top": 0.7}
            size_hint: 0.8, 0.58
            GridLayout:
                id: lista_fotos_perfil
                cols: 3
                size_hint_y: None
                spacing: 5, 5
                height: self.minimum_height
                row_default_height: "90dp"
                row_force_default: True

        FloatLayout:
            pos_hint: {"right": 1, "top":0.15}
            size_hint: 1, 0.15
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#006D7E")
                Rectangle:
                    size: self.size
                    pos: self.pos
# imagem de botão para voltar para a home
            ImageButton:
                pos_hint: {"right": 0.2 , "top": 0.9}
                size_hint:  0.2, 0.8
                source: "icones/voltar.png"
                on_release: app.mudar_tela("ajustespage")