<TodasVendas>:
    FloatLayout:
        canvas.before:
            Rectangle:
                size: self.size
                pos: self.pos
                source: "icones/bg1.png"

        Label:
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: self.size
                    source: "icones/botao_fino.png"
            pos_hint: {"right":0.85, "top":0.95}
            size_hint: 0.7, 0.2
            text: "Total de vendas: R$"
            id: label_total_vendas
            markup: True

        ScrollView:
            pos_hint: {"right": 1,"top": 0.75}
            size_hint: 1, 0.63
            GridLayout:
                id: lista_vendas
                cols: 1
                spacing: "8dp"          # Adiciona espaço entre cada card de venda
                padding: ["10dp", "5dp"] # Margem nas laterais do scroll
                size_hint_y: None
                height: self.minimum_height
                row_default_height: "105dp"  # Aumentado para não encostar na barra inferior
                row_force_default: True

        FloatLayout:
            pos_hint: {"right": 1, "top":0.15}
            size_hint: 1, 0.15
            canvas:
                Color:
                    rgb: utils.get_color_from_hex("#006D7E")
                Rectangle:
                    size: self.size
                    pos: self.pos
            # imagem de botão para voltar para a home
            ImageButton:
                pos_hint: {"right": 0.2 , "top": 0.9}
                size_hint:  0.2, 0.8
                source: "icones/voltar.png"
                on_release: app.sair_todas_vendas("ajustespage")